package dominio;
// Generated 11-01-2014 10:14:49 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClientetarjetaId generated by hbm2java
 */
@Embeddable
public class ClientetarjetaId  implements java.io.Serializable {


     private int idCliente;
     private int idTarjetaCredito;

    public ClientetarjetaId() {
    }

    public ClientetarjetaId(int idCliente, int idTarjetaCredito) {
       this.idCliente = idCliente;
       this.idTarjetaCredito = idTarjetaCredito;
    }
   


    @Column(name="idCliente", nullable=false)
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }


    @Column(name="idTarjetaCredito", nullable=false)
    public int getIdTarjetaCredito() {
        return this.idTarjetaCredito;
    }
    
    public void setIdTarjetaCredito(int idTarjetaCredito) {
        this.idTarjetaCredito = idTarjetaCredito;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ClientetarjetaId) ) return false;
		 ClientetarjetaId castOther = ( ClientetarjetaId ) other; 
         
		 return (this.getIdCliente()==castOther.getIdCliente())
 && (this.getIdTarjetaCredito()==castOther.getIdTarjetaCredito());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdCliente();
         result = 37 * result + this.getIdTarjetaCredito();
         return result;
   }   


}


