package dominio;
// Generated 11-01-2014 10:14:49 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tarjetacredito generated by hbm2java
 */
@Entity
@Table(name="tarjetacredito"
    ,catalog="g1"
)
public class Tarjetacredito  implements java.io.Serializable {


     private Integer idTarjetaCredito;
     private String nombreTarjeta;
     private BigDecimal limiteCreditoMin;
     private BigDecimal limiteCreditoMax;
     private String nombreEmisor;
     private Date fechaIngreso;
     private BigDecimal tasaInteres;
     private Set clientetarjetas = new HashSet(0);

    public Tarjetacredito() {
    }

	
    public Tarjetacredito(String nombreTarjeta, BigDecimal limiteCreditoMin, BigDecimal limiteCreditoMax, String nombreEmisor, Date fechaIngreso, BigDecimal tasaInteres) {
        this.nombreTarjeta = nombreTarjeta;
        this.limiteCreditoMin = limiteCreditoMin;
        this.limiteCreditoMax = limiteCreditoMax;
        this.nombreEmisor = nombreEmisor;
        this.fechaIngreso = fechaIngreso;
        this.tasaInteres = tasaInteres;
    }
    public Tarjetacredito(String nombreTarjeta, BigDecimal limiteCreditoMin, BigDecimal limiteCreditoMax, String nombreEmisor, Date fechaIngreso, BigDecimal tasaInteres, Set clientetarjetas) {
       this.nombreTarjeta = nombreTarjeta;
       this.limiteCreditoMin = limiteCreditoMin;
       this.limiteCreditoMax = limiteCreditoMax;
       this.nombreEmisor = nombreEmisor;
       this.fechaIngreso = fechaIngreso;
       this.tasaInteres = tasaInteres;
       this.clientetarjetas = clientetarjetas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idTarjetaCredito", unique=true, nullable=false)
    public Integer getIdTarjetaCredito() {
        return this.idTarjetaCredito;
    }
    
    public void setIdTarjetaCredito(Integer idTarjetaCredito) {
        this.idTarjetaCredito = idTarjetaCredito;
    }

    
    @Column(name="nombre_tarjeta", nullable=false, length=45)
    public String getNombreTarjeta() {
        return this.nombreTarjeta;
    }
    
    public void setNombreTarjeta(String nombreTarjeta) {
        this.nombreTarjeta = nombreTarjeta;
    }

    
    @Column(name="limite_credito_min", nullable=false, precision=11)
    public BigDecimal getLimiteCreditoMin() {
        return this.limiteCreditoMin;
    }
    
    public void setLimiteCreditoMin(BigDecimal limiteCreditoMin) {
        this.limiteCreditoMin = limiteCreditoMin;
    }

    
    @Column(name="limite_credito_max", nullable=false, precision=11)
    public BigDecimal getLimiteCreditoMax() {
        return this.limiteCreditoMax;
    }
    
    public void setLimiteCreditoMax(BigDecimal limiteCreditoMax) {
        this.limiteCreditoMax = limiteCreditoMax;
    }

    
    @Column(name="nombre_emisor", nullable=false, length=45)
    public String getNombreEmisor() {
        return this.nombreEmisor;
    }
    
    public void setNombreEmisor(String nombreEmisor) {
        this.nombreEmisor = nombreEmisor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_ingreso", nullable=false, length=10)
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    
    @Column(name="tasa_interes", nullable=false, precision=7)
    public BigDecimal getTasaInteres() {
        return this.tasaInteres;
    }
    
    public void setTasaInteres(BigDecimal tasaInteres) {
        this.tasaInteres = tasaInteres;
    }
/*
//@OneToMany(fetch=FetchType.LAZY, mappedBy="tarjetacredito")
    public Set getClientetarjetas() {
        return this.clientetarjetas;
    }
    
    public void setClientetarjetas(Set clientetarjetas) {
        this.clientetarjetas = clientetarjetas;
    }



*/
}


