package dominio;
// Generated 11-01-2014 10:14:49 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tipocliente generated by hbm2java
 */
@Entity
@Table(name="tipocliente"
    ,catalog="g1"
)
public class Tipocliente  implements java.io.Serializable {


     private String idTipoCliente;
     private String DTipoCliente;
     private Date fechIngres;
     private Set clientes = new HashSet(0);

    public Tipocliente() {
    }

	
    public Tipocliente(String idTipoCliente, String DTipoCliente, Date fechIngres) {
        this.idTipoCliente = idTipoCliente;
        this.DTipoCliente = DTipoCliente;
        this.fechIngres = fechIngres;
    }
    public Tipocliente(String idTipoCliente, String DTipoCliente, Date fechIngres, Set clientes) {
       this.idTipoCliente = idTipoCliente;
       this.DTipoCliente = DTipoCliente;
       this.fechIngres = fechIngres;
       this.clientes = clientes;
    }
   
     @Id 

    
    @Column(name="idTipoCliente", unique=true, nullable=false, length=3)
    public String getIdTipoCliente() {
        return this.idTipoCliente;
    }
    
    public void setIdTipoCliente(String idTipoCliente) {
        this.idTipoCliente = idTipoCliente;
    }

    
    @Column(name="d_tipo_cliente", nullable=false, length=25)
    public String getDTipoCliente() {
        return this.DTipoCliente;
    }
    
    public void setDTipoCliente(String DTipoCliente) {
        this.DTipoCliente = DTipoCliente;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fech_ingres", nullable=false, length=10)
    public Date getFechIngres() {
        return this.fechIngres;
    }
    
    public void setFechIngres(Date fechIngres) {
        this.fechIngres = fechIngres;
    }

//@OneToMany(fetch=FetchType.LAZY, mappedBy="tipocliente")
  /*  public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }



*/
}


